name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./backend
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend
        path: backend/bin/Release/net6.0

  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend.unittests
    - name: Build test
      run: dotnet build --no-restore --configuration Release
      working-directory: ./backend.unittests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./backend.unittests
      
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build
      working-directory: ./frontend
      run: |
        npm install
        npx webpack --config ./webpack.production.config.js
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: frontend/dist.production
        
  combine-artifacts:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: frontend
        path: frontend/dist.production
    - uses: actions/download-artifact@v3
      with:
        name: backend
        path: backend/bin/Release/net6.0
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dockerfile
        path: |
          frontend/dist.production
          backend/bin/Release/net6.0
          Dockerfile
