name: Publish development Docker image

on:
  push:
    branches: [ "develop" ]

jobs:
  build-image:
    uses: assetgrid/assetgridapp/.github/workflows/build.yml@main

  publish-image:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: dockerfile
          path: ./docker

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
            assetgrid/assetgrid
          tags: |
            type=ref,event=branch
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64, linux/arm64, linux/arm/v8
          labels: ${{ steps.meta.outputs.labels }}
